FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000
ENV AWS_ACCESS_KEY_ID=<Your-Access-Key>
ENV AWS_SECRET_ACCESS_KEY=<Secret-Access-Key>
ENV AWS_DEFAULT_REGION=us-east-1

CMD [ "flask", "run" ]
